function Hd = butter20
%BUTTER20 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 16-Sep-2021 14:24:25

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 2000;  % Sampling Frequency

N  = 2;   % Order
Fc = 20;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% 获取传递函数值。
[b, a] = tf(Hd);

% 转换为单一滤波器。
Hd = dfilt.df2(b, a);



% [EOF]
