function Hd = butter50
%BUTTER50 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 12-Sep-2021 16:19:16

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 2000;  % Sampling Frequency

N  = 2;   % Order
Fc = 50;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% 获取传递函数值。
[b, a] = tf(Hd);

% 转换为单一滤波器。
Hd = dfilt.df2(b, a);



% [EOF]
